# people.toml

[table]
contracts = [
  { rule = "row_count", min = 1_500_000, max = 2_000_000 }
]

[[columns]]
name = "person_id"
contracts = [
  { rule = "not_null" },
  { rule = "unique" },
  { rule = "pattern", pattern = "^[0-9a-fA-F-]{36}$" }
]

[[columns]]
name = "age"
contracts = [
  { rule = "range", min = 0, max = 120 },
  { rule = "outlier_sigma", sigma = 3.0 }
]

[[compound_unique]]
columns = ["household_id", "person_id"]
