
name = "regions"
version = "0.1.0"

[[columns]]
name = "Region_ID"
contracts = [
  { rule = "not_null" },
  { rule = "unique" },
  { rule = "range", min = 1, max = 9999 },
  { rule = "outlier_sigma", sigma = 2.5}
]

# Example: ensure Ancient_Name is not empty
[[columns]]
name = "Ancient_Name"
contracts = [
  { rule = "not_null" }
]

# Example: Current_Faction must be present
[[columns]]
name = "Current_Faction"
contracts = [
  { rule = "not_null" },
  { rule = "in_set", values = ["Empyrean Synod", "Praxis Directorate", "Vesperian Concord", "Factionless"] }
]

# Example: Era_Tag should match a pattern (e.g. uppercase letters)
[[columns]]
name = "Era_Tag"
contracts = [
  { rule = "pattern", pattern = "^[A-Z][a-z]+$" }
]

# Example: Full_Name must not be null
[[columns]]
name = "Full_Name"
contracts = [
  { rule = "not_null" }
]

# Example: Colloquial_Name optional, but if present must be <= 50 chars
[[columns]]
name = "Colloquial_Name"
contracts = [
  { rule = "max_length", value = 50 }
]

[[columns]]
name = "Founding_Era"
contracts = [
  { rule = "in_set", values = ["Pre-Accord", "Accord-Era", "Post-War"] }
]

# Example: Density_Tier should be categorical
[[columns]]
name = "Density_Tier"
contracts = [
  { rule = "in_set", values = ["Settled", "Dense", "Sparse", "Wastes"] }
]

# Example: Capital must not be null
[[columns]]
name = "Capital"
contracts = [
  { rule = "not_null" }
]

# Example: Primary_Industry must be present
[[columns]]
name = "Primary_Industry"
contracts = [
  { rule = "not_null" }
]

# Example: Founding_Story is free text, no contract yet
[[columns]]
name = "Founding_Story"
contracts = []

# Example: Vote_History_Last3 should be categorical
[[columns]]
name = "Vote_History_Last3"
contracts = [
  { rule = "not_null" }
]

# Example: Key_Pressure_Points optional
[[columns]]
name = "Key_Pressure_Points"
contracts = []

[[columns]]
name = "Unbound_Presence"
contracts = [
  { rule = "in_set", values = ["Latent", "Active", "Sympathetic", "Tolerated", "Passive", "Dominant", "Folk Hero", "Whisper Network", "None"] }
]
